.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_80118350

dlabel D_80118350
    /* 0 80118350 4C455353 */ .word 0x5353454C
    /* 4 80118354 4F4E0000 */ .word 0x00004E4F
enddlabel D_80118350

.align 2
nonmatching D_80118358

dlabel D_80118358
    /* 8 80118358 */ .asciz "Text offsets"
    /* 54657874206F66667365747300000000 */
.align 2
enddlabel D_80118358

nonmatching D_80118368

dlabel D_80118368
    /* 18 80118368 01000000 */ .word 0x00000001
    /* 1C 8011836C FFFFFFFF */ .word 0xFFFFFFFF
    /* 20 80118370 FFFFFFFF */ .word 0xFFFFFFFF
    /* 24 80118374 00000000 */ .word 0x00000000
enddlabel D_80118368

nonmatching D_80118378

dlabel D_80118378
    /* 28 80118378 00000000 */ .word 0x00000000
    /* 2C 8011837C 01000000 */ .word 0x00000001
    /* 30 80118380 FFFFFFFF */ .word 0xFFFFFFFF
    /* 34 80118384 00000000 */ .word 0x00000000
enddlabel D_80118378

.align 2
nonmatching D_80118388

dlabel D_80118388
    /* 38 80118388 */ .asciz "crateHeld"
    /* 637261746548656C64000000 */
.align 2
enddlabel D_80118388

nonmatching D_80118394

dlabel D_80118394
    /* 44 80118394 616D6D6F */ .word 0x6F6D6D61
    /* 48 80118398 00000000 */ .word 0x00000000
enddlabel D_80118394

.align 2
nonmatching D_8011839C

dlabel D_8011839C
    /* 4C 8011839C */ .asciz "crateOnPad"
    /* 63726174654F6E5061640000 */
.align 2
enddlabel D_8011839C

.align 2
nonmatching D_801183A8

dlabel D_801183A8
    /* 58 801183A8 */ .asciz "swapping"
    /* 7377617070696E6700000000 */
.align 2
enddlabel D_801183A8

.align 2
nonmatching D_801183B4

dlabel D_801183B4
    /* 64 801183B4 */ .asciz "freeBuild"
    /* 667265654275696C64000000 */
.align 2
enddlabel D_801183B4

.align 2
nonmatching D_801183C0

dlabel D_801183C0
    /* 70 801183C0 */ .asciz "gotWeapon"
    /* 676F74576561706F6E000000 */
.align 2
enddlabel D_801183C0

.align 2
nonmatching D_801183CC

dlabel D_801183CC
    /* 7C 801183CC */ .asciz "gotBuddy"
    /* 676F74427564647900000000 */
.align 2
enddlabel D_801183CC

.align 2
nonmatching D_801183D8

dlabel D_801183D8
    /* 88 801183D8 */ .asciz "couldBuild"
    /* 636F756C644275696C640000 */
.align 2
enddlabel D_801183D8

.align 2
nonmatching D_801183E4

dlabel D_801183E4
    /* 94 801183E4 */ .asciz "hasBuilt"
    /* 6861734275696C7400000000 */
.align 2
enddlabel D_801183E4

.align 2
nonmatching D_801183F0

dlabel D_801183F0
    /* A0 801183F0 */ .asciz "allclear"
    /* 616C6C636C65617200000000 */
.align 2
enddlabel D_801183F0

.align 2
nonmatching D_801183FC

dlabel D_801183FC
    /* AC 801183FC */ .asciz "baseorder"
    /* 626173656F72646572000000 */
.align 2
enddlabel D_801183FC

.align 2
nonmatching D_80118408

dlabel D_80118408
    /* B8 80118408 */ .asciz "lookAtBuddy"
    /* 6C6F6F6B4174427564647900 */
.align 2
enddlabel D_80118408

.align 2
nonmatching D_80118414

dlabel D_80118414
    /* C4 80118414 */ .asciz "switches"
    /* 737769746368657300000000 */
.align 2
enddlabel D_80118414

.align 2
nonmatching D_80118420

dlabel D_80118420
    /* D0 80118420 */ .asciz "buttonPressed"
    /* 627574746F6E50726573736564000000 */
.align 2
enddlabel D_80118420

.align 2
nonmatching D_80118430

dlabel D_80118430
    /* E0 80118430 */ .asciz "toyOnFloor"
    /* 746F794F6E466C6F6F720000 */
.align 2
enddlabel D_80118430

.align 2
nonmatching D_8011843C

dlabel D_8011843C
    /* EC 8011843C */ .asciz "buddyJump"
    /* 62756464794A756D70000000 */
.align 2
enddlabel D_8011843C

.align 2
nonmatching D_80118448

dlabel D_80118448
    /* F8 80118448 */ .asciz "isTowing"
    /* 6973546F77696E6700000000 */
.align 2
enddlabel D_80118448

.align 2
nonmatching D_80118454

dlabel D_80118454
    /* 104 80118454 */ .asciz "timerOver"
    /* 74696D65724F766572000000 */
.align 2
enddlabel D_80118454

.align 2
nonmatching D_80118460

dlabel D_80118460
    /* 110 80118460 */ .asciz "counterEquals"
    /* 636F756E746572457175616C73000000 */
.align 2
enddlabel D_80118460

.align 2
nonmatching D_80118470

dlabel D_80118470
    /* 120 80118470 */ .asciz "buddyCloseTo"
    /* 6275646479436C6F7365546F00000000 */
.align 2
enddlabel D_80118470

.align 2
nonmatching D_80118480

dlabel D_80118480
    /* 130 80118480 */ .asciz "buildOrder"
    /* 6275696C644F726465720000 */
.align 2
enddlabel D_80118480

.align 2
nonmatching D_8011848C

dlabel D_8011848C
    /* 13C 8011848C */ .asciz "strafing"
    /* 7374726166696E6700000000 */
.align 2
enddlabel D_8011848C

.align 2
nonmatching D_80118498

dlabel D_80118498
    /* 148 80118498 */ .asciz "strafeTargetting"
    /* 73747261666554617267657474696E6700000000 */
.align 2
enddlabel D_80118498

.align 2
nonmatching D_801184AC

dlabel D_801184AC
    /* 15C 801184AC */ .asciz "inVehicle"
    /* 696E56656869636C65000000 */
.align 2
enddlabel D_801184AC

.align 2
nonmatching D_801184B8

dlabel D_801184B8
    /* 168 801184B8 */ .asciz "ankhOwned"
    /* 616E6B684F776E6564000000 */
.align 2
enddlabel D_801184B8

.align 2
nonmatching D_801184C4

dlabel D_801184C4
    /* 174 801184C4 */ .asciz "scored"
    /* 73636F7265640000 */
.align 2
enddlabel D_801184C4

.align 2
nonmatching D_801184CC

dlabel D_801184CC
    /* 17C 801184CC */ .asciz "dogWounded"
    /* 646F67576F756E6465640000 */
.align 2
enddlabel D_801184CC

.align 2
nonmatching D_801184D8

dlabel D_801184D8
    /* 188 801184D8 */ .asciz "buddyWounded"
    /* 6275646479576F756E64656400000000 */
.align 2
enddlabel D_801184D8

.align 2
nonmatching D_801184E8

dlabel D_801184E8
    /* 198 801184E8 */ .asciz "damagedStatic"
    /* 64616D61676564537461746963000000 */
.align 2
enddlabel D_801184E8

.align 2
nonmatching D_801184F8

dlabel D_801184F8
    /* 1A8 801184F8 */ .asciz "shatteredStatics"
    /* 7368617474657265645374617469637300000000 */
.align 2
enddlabel D_801184F8

.align 2
nonmatching D_8011850C

dlabel D_8011850C
    /* 1BC 8011850C */ .asciz "destroyedStatics"
    /* 64657374726F7965645374617469637300000000 */
.align 2
enddlabel D_8011850C

.align 2
nonmatching D_80118520

dlabel D_80118520
    /* 1D0 80118520 */ .asciz "equippedWeapon"
    /* 6571756970706564576561706F6E0000 */
.align 2
enddlabel D_80118520

.align 2
nonmatching D_80118530

dlabel D_80118530
    /* 1E0 80118530 */ .asciz "stump"
    /* 7374756D70000000 */
.align 2
enddlabel D_80118530

.align 2
nonmatching D_80118538

dlabel D_80118538
    /* 1E8 80118538 */ .asciz "zones"
    /* 7A6F6E6573000000 */
.align 2
enddlabel D_80118538

.align 2
nonmatching D_80118540

dlabel D_80118540
    /* 1F0 80118540 */ .asciz "msg"
    /* 6D736700 */
.align 2
enddlabel D_80118540

.align 2
nonmatching D_80118544

dlabel D_80118544
    /* 1F4 80118544 */ .asciz "x"
    /* 78000000 */
.align 2
enddlabel D_80118544

.align 2
nonmatching D_80118548

dlabel D_80118548
    /* 1F8 80118548 */ .asciz "wait"
    /* 7761697400000000 */
.align 2
enddlabel D_80118548

.align 2
nonmatching D_80118550

dlabel D_80118550
    /* 200 80118550 */ .asciz "waitNOT"
    /* 776169744E4F5400 */
.align 2
enddlabel D_80118550

.align 2
nonmatching D_80118558

dlabel D_80118558
    /* 208 80118558 */ .asciz "if"
    /* 69660000 */
.align 2
enddlabel D_80118558

.align 2
nonmatching D_8011855C

dlabel D_8011855C
    /* 20C 8011855C */ .asciz "ifNOT"
    /* 69664E4F54000000 */
.align 2
enddlabel D_8011855C

.align 2
nonmatching D_80118564

dlabel D_80118564
    /* 214 80118564 */ .asciz "healDog"
    /* 6865616C446F6700 */
.align 2
enddlabel D_80118564

.align 2
nonmatching D_8011856C

dlabel D_8011856C
    /* 21C 8011856C */ .asciz "resetScore"
    /* 726573657453636F72650000 */
.align 2
enddlabel D_8011856C

.align 2
nonmatching D_80118578

dlabel D_80118578
    /* 228 80118578 */ .asciz "goto"
    /* 676F746F00000000 */
.align 2
enddlabel D_80118578

.align 2
nonmatching D_80118580

dlabel D_80118580
    /* 230 80118580 */ .asciz "ULammo"
    /* 554C616D6D6F0000 */
.align 2
enddlabel D_80118580

.align 2
nonmatching D_80118588

dlabel D_80118588
    /* 238 80118588 */ .asciz "setCounterMax"
    /* 736574436F756E7465724D6178000000 */
.align 2
enddlabel D_80118588

nonmatching D_80118598

dlabel D_80118598
    /* 248 80118598 75736550 */ .word 0x50657375
    /* 24C 8011859C 61640000 */ .word 0x00006461
enddlabel D_80118598

.align 2
nonmatching D_801185A0

dlabel D_801185A0
    /* 250 801185A0 */ .asciz "frame"
    /* 6672616D65000000 */
.align 2
enddlabel D_801185A0

.align 2
nonmatching D_801185A8

dlabel D_801185A8
    /* 258 801185A8 */ .asciz "crates"
    /* 6372617465730000 */
.align 2
enddlabel D_801185A8

.align 2
nonmatching D_801185B0

dlabel D_801185B0
    /* 260 801185B0 */ .asciz "superCrate"
    /* 737570657243726174650000 */
.align 2
enddlabel D_801185B0

.align 2
nonmatching D_801185BC

dlabel D_801185BC
    /* 26C 801185BC */ .asciz "timer"
    /* 74696D6572000000 */
.align 2
enddlabel D_801185BC

.align 2
nonmatching D_801185C4

dlabel D_801185C4
    /* 274 801185C4 */ .asciz "staticInv"
    /* 737461746963496E76000000 */
.align 2
enddlabel D_801185C4

.align 2
nonmatching D_801185D0

dlabel D_801185D0
    /* 280 801185D0 */ .asciz "health"
    /* 6865616C74680000 */
.align 2
enddlabel D_801185D0

.align 2
nonmatching D_801185D8

dlabel D_801185D8
    /* 288 801185D8 */ .asciz "ULhealth"
    /* 554C6865616C746800000000 */
.align 2
enddlabel D_801185D8

.align 2
nonmatching D_801185E4

dlabel D_801185E4
    /* 294 801185E4 */ .asciz "Immobile"
    /* 496D6D6F62696C6500000000 */
.align 2
enddlabel D_801185E4

.align 2
nonmatching D_801185F0

dlabel D_801185F0
    /* 2A0 801185F0 */ .asciz "ImmobileAll"
    /* 496D6D6F62696C65416C6C00 */
.align 2
enddlabel D_801185F0

.align 2
nonmatching D_801185FC

dlabel D_801185FC
    /* 2AC 801185FC */ .asciz "createBuddy"
    /* 637265617465427564647900 */
.align 2
enddlabel D_801185FC

.align 2
nonmatching D_80118608

dlabel D_80118608
    /* 2B8 80118608 */ .asciz "createVehicle"
    /* 63726561746556656869636C65000000 */
.align 2
enddlabel D_80118608

nonmatching D_80118618

dlabel D_80118618
    /* 2C8 80118618 62757474 */ .word 0x74747562
    /* 2CC 8011861C 6F6E5345 */ .word 0x45536E6F
    /* 2D0 80118620 54000000 */ .word 0x00000054
enddlabel D_80118618

.align 2
nonmatching D_80118624

dlabel D_80118624
    /* 2D4 80118624 */ .asciz "buttonON"
    /* 627574746F6E4F4E00000000 */
.align 2
enddlabel D_80118624

.align 2
nonmatching D_80118630

dlabel D_80118630
    /* 2E0 80118630 */ .asciz "buttonOFF"
    /* 627574746F6E4F4646000000 */
.align 2
enddlabel D_80118630

.align 2
nonmatching D_8011863C

dlabel D_8011863C
    /* 2EC 8011863C */ .asciz "makeCrates"
    /* 6D616B654372617465730000 */
.align 2
enddlabel D_8011863C

.align 2
nonmatching D_80118648

dlabel D_80118648
    /* 2F8 80118648 */ .asciz "healBuddy"
    /* 6865616C4275646479000000 */
.align 2
enddlabel D_80118648

.align 2
nonmatching D_80118654

dlabel D_80118654
    /* 304 80118654 */ .asciz "moveBuddy"
    /* 6D6F76654275646479000000 */
.align 2
enddlabel D_80118654

nonmatching D_80118660

dlabel D_80118660
    /* 310 80118660 63726561 */ .word 0x61657263
    /* 314 80118664 74655374 */ .word 0x74536574
    /* 318 80118668 61746963 */ .word 0x63697461
    /* 31C 8011866C 00000000 */ .word 0x00000000
enddlabel D_80118660

.align 2
nonmatching D_80118670

dlabel D_80118670
    /* 320 80118670 */ .asciz "createDog"
    /* 637265617465446F67000000 */
.align 2
enddlabel D_80118670

nonmatching func_8011867C

dlabel func_8011867C
    /* 32C 8011867C 00008790 */ .word 0x90870000
    /* 330 80118680 01008424 */ .word 0x24840001
    /* 334 80118684 0000A390 */ .word 0x90A30000
    /* 338 80118688 9FFFE224 */ .word 0x24E2FF9F
    /* 33C 8011868C 1A00422C */ .word 0x2C42001A
    /* 340 80118690 03004010 */ .word 0x10400003
    /* 344 80118694 0100A524 */ .word 0x24A50001
    /* 348 80118698 E000E224 */ .word 0x24E200E0
    /* 34C 8011869C FF004730 */ .word 0x304700FF
    /* 350 801186A0 9FFF6224 */ .word 0x2462FF9F
    /* 354 801186A4 1A00422C */ .word 0x2C42001A
    /* 358 801186A8 02004010 */ .word 0x10400002
    /* 35C 801186AC E0006224 */ .word 0x246200E0
    /* 360 801186B0 FF004330 */ .word 0x304300FF
    /* 364 801186B4 0700E314 */ .word 0x14E30007
    /* 368 801186B8 21100000 */ .word 0x00001021
    /* 36C 801186BC 0300E010 */ .word 0x10E00003
    /* 370 801186C0 FFFFC624 */ .word 0x24C6FFFF
    /* 374 801186C4 EDFFC014 */ .word 0x14C0FFED
    /* 378 801186C8 00000000 */ .word 0x00000000
    /* 37C 801186CC 0800E003 */ .word 0x03E00008
    /* 380 801186D0 01000224 */ .word 0x24020001
    /* 384 801186D4 0800E003 */ .word 0x03E00008
    /* 388 801186D8 00000000 */ .word 0x00000000
enddlabel func_8011867C

nonmatching func_801186DC

dlabel func_801186DC
    /* 38C 801186DC 1280023C */ .word 0x3C028012
    /* 390 801186E0 01000324 */ .word 0x24030001
    /* 394 801186E4 34BF458C */ .word 0x8C45BF34
    /* 398 801186E8 04188300 */ .word 0x00831804
    /* 39C 801186EC 2528A300 */ .word 0x00A32825
    /* 3A0 801186F0 0800E003 */ .word 0x03E00008
    /* 3A4 801186F4 34BF45AC */ .word 0xAC45BF34
enddlabel func_801186DC

nonmatching func_801186F8

dlabel func_801186F8
    /* 3A8 801186F8 1280023C */ .word 0x3C028012
    /* 3AC 801186FC 01000324 */ .word 0x24030001
    /* 3B0 80118700 04188300 */ .word 0x00831804
    /* 3B4 80118704 34BF448C */ .word 0x8C44BF34
    /* 3B8 80118708 27180300 */ .word 0x00031827
    /* 3BC 8011870C 24208300 */ .word 0x00832024
    /* 3C0 80118710 0800E003 */ .word 0x03E00008
    /* 3C4 80118714 34BF44AC */ .word 0xAC44BF34
    /* 3C8 80118718 1280033C */ .word 0x3C038012
    /* 3CC 8011871C 00008594 */ .word 0x94850000
    /* 3D0 80118720 34BF6294 */ .word 0x9462BF34
    /* 3D4 80118724 00000000 */ .word 0x00000000
    /* 3D8 80118728 2428A200 */ .word 0x00A22824
    /* 3DC 8011872C 1280023C */ .word 0x3C028012
    /* 3E0 80118730 000085A4 */ .word 0xA4850000
    /* 3E4 80118734 38BF438C */ .word 0x8C43BF38
    /* 3E8 80118738 00000000 */ .word 0x00000000
    /* 3EC 8011873C 03006010 */ .word 0x10600003
    /* 3F0 80118740 02120500 */ .word 0x00051202
    /* 3F4 80118744 0800E003 */ .word 0x03E00008
    /* 3F8 80118748 21100000 */ .word 0x00001021
    /* 3FC 8011874C 01004238 */ .word 0x38420001
enddlabel func_801186F8
